//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUBLISHINGHOUSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.PublicationOrder = new HashSet<PublicationOrder>();
        }
    
        public long BookID { get; set; }
        public string BookTitle { get; set; }
        public long GenreID { get; set; }
        public int PagesAmount { get; set; }
        public string Author { get; set; }
        public double Price { get; set; }
        public string Remark { get; set; }
        public long Edition { get; set; }
        public string BookBinding { get; set; }
        public string PagesColor { get; set; }
        public string PagesFormat { get; set; }
    
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicationOrder> PublicationOrder { get; set; }
    }
}
