//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUBLISHINGHOUSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicationOrder
    {
        public long OrderID { get; set; }
        public long ClientID { get; set; }
        public long BookID { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public int Edition { get; set; }
        public double TotalCost { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Client Client { get; set; }
    }
}
